addSbtPlugin("com.eed3si9n"      % "sbt-assembly"    % "0.14.3")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.8.5")
addSbtPlugin("com.typesafe.sbt"  % "sbt-multi-jvm"   % "0.3.11")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.5.1")
addSbtPlugin("me.lessis"         % "bintray-sbt"     % "0.3.0")
addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.6.0")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"      % "1.3.0")
